#ifndef RISC_V_SEC_EXCEPTION_H
#define RISC_V_SEC_EXCEPTION_H

enum exception {
  INST_ADDR_MISALIGNED  = 0,
  INST_ACCESS_FAULT     = 1,
  ILLEGAL_INSTRUCTION   = 2,
  BREAKPOINT            = 3,
  LOAD_ADDR_MISALIGNED  = 4,
  LOAD_ACCESS_FAULT     = 5,
  STORE_ADDR_MISALIGNED = 6,
  STORE_ACCESS_FAULT    = 7,
  ENV_CALL_FROM_U       = 8,
  ENV_CALL_FROM_S       = 9,
  ENV_CALL_FROM_H       = 10,
  ENV_CALL_FROM_M       = 11,
  INST_PAGEFAULT        = 12,
  LOAD_PAGEFAULT        = 13,
  STORE_PAGEFAULT       = 15,
};

enum interrupt {
  USER_SOFTWARE_INT     = 0,
  SUPERV_SOFTWARE_INT   = 1,
  MACHINE_SOFTWARE_INT  = 3,
  USER_TIMER_INT        = 4,
  SUPERV_TIMER_INT      = 5,
  MACHINE_TIMER_INT     = 7,
  USER_EXTERNAL_INT     = 8,
  SUPERV_EXTERNAL_INT   = 9,
  MACHINE_EXTERNAL_INT  = 11,
};

#endif
